---
title: "Nested Hierarchical visualization"
output: html_document
date: "2024-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gtable)
library(ggplot2)
library(patchwork)
library(gridExtra)
library(grid)
library(lattice)
library(ggridges)
library(tidyverse)

```

## R Markdown

```{r, fig.height=7.2, fig.width=7.2}

set.seed(123)


void_with_x <- function(base_size = 12, base_family = "") {
  theme_void(base_size = base_size, base_family = base_family) +
    theme(
      axis.title.x = element_text(hjust = 0.5),
      plot.subtitle = element_blank(),
      plot.caption = element_blank()
    )
}


data <- data.frame(value = rnorm(10000,0,2), value2 = rnorm(100))



datap_a = data.frame(value = rnorm(10000,0,6), parameter = "alpha")
datap_b = data.frame(value = rnorm(10000,2,8), parameter = "beta")
datap_l = data.frame(value = rnorm(10000,7,3), parameter = "lambda")

datap = rbind(datap_a,datap_b,datap_l)


pop <- ggplot(data = datap, aes(x = value, y = 0.1)) +
  geom_density_ridges(aes(fill = parameter), color = "black", alpha = 0.9,bandwidth = 2) +
  xlab("Parameters (Population)")+
  void_with_x()+
  theme(text = element_text(size = 10),legend.position = "none")+
  scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))



datap1_a = data.frame(value = rnorm(10000,0,4), parameter = "alpha")
datap1_b = data.frame(value = rnorm(10000,2,3), parameter = "beta")
datap1_l = data.frame(value = rnorm(10000,-1,0.5), parameter = "lambda")

datap1 = rbind(datap1_a,datap1_b,datap1_l)


sub1 <- ggplot(datap1, aes(x = value, y = 0.1)) +
  geom_density_ridges(aes(fill = parameter),bandwidth = 2, color = "black", alpha = 0.7) +  
  xlab("Parameters (subject 1)")+
  void_with_x()+
  theme(text = element_text(size = 10),legend.position = "none")+
  scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))

sub2 <- ggplot(datap1, aes(x = value, y = 0.1)) +
  geom_density_ridges(aes(fill = parameter),bandwidth = 2, color = "black", alpha = 0.7) +  
  xlab("Parameters (subject 2)")+
  void_with_x()+
  theme(text = element_text(size = 10),legend.position = "none")+
  scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))


datap2_a = data.frame(value = rnorm(10000,0,2), parameter = "alpha")
datap2_b = data.frame(value = rnorm(10000,2,1.5), parameter = "beta")
datap2_l = data.frame(value = rnorm(10000,-1,0.5), parameter = "lambda")

datap2 = rbind(datap2_a,datap2_b,datap2_l)




      
sub1_p1 <- ggplot(datap2, aes(x = value, y = 0.1)) +
  geom_density_ridges(binwidth = 0.5, aes(fill = parameter), color = "black", alpha = 0.5, bandwith = 1) +
  xlab("Parameters (session 1)")+
  void_with_x()+
  theme(text = element_text(size = 8),
        legend.position = "none")+
    scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))


sub1_p2 <- ggplot(datap2, aes(x = value, y = 0.1)) +
  geom_density_ridges(binwidth = 0.5, aes(fill = parameter), color = "black", alpha = 0.5, bandwith = 1) +
  xlab("Parameters (session 2)")+
  void_with_x()+
  theme(text = element_text(size = 8),
        legend.position = "none")+
    scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))


sub2_p1 <- ggplot(datap2, aes(x = value, y = 0.1)) +
  geom_density_ridges(binwidth = 0.5, aes(fill = parameter), color = "black", alpha = 0.5, bandwith = 1) +
  xlab("Parameters (session 1)")+
  void_with_x()+
  theme(text = element_text(size = 8),
        legend.position = "none")+
    scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))



sub2_p2 <- ggplot(datap2, aes(x = value, y = 0.1)) +
  geom_density_ridges(binwidth = 0.5, aes(fill = parameter), color = "black", alpha = 0.5, bandwidth = 1) +
  xlab("Parameters (session 2)")+
  void_with_x()+
  theme(text = element_text(size = 8),
        legend.position = "none")+
    scale_fill_manual(values = c("#058cd7","#00995e","#fb7da8"))


x = seq(-20,20,by = 1)
  
psycho = function(x, alpha,beta,lambda){
  
  return(brms::inv_logit_scaled(lambda) / 2 + (1 - 2 * brms::inv_logit_scaled(lambda) / 2) * (0.5 + 0.5 * pracma::erf(((x - alpha) / (exp(beta) * sqrt(2))))))
  
}


ses3 = data.frame(x = x, y = rbinom(length(x),1,psycho(x,-5,2,-3)), session = 1) 
ses4 = data.frame(x = x, y = rbinom(length(x),1,psycho(x,-10,1.5,-2.5)), session = 2) 

scatter1 <- rbind(ses3,ses4) %>% mutate(session = as.factor(session)) %>% 
  ggplot(aes(x=x, y=y, col = session, fill = session)) +
  geom_point() +
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial")) +theme_classic()+
  theme(text = element_text(size = 10),
        legend.position = c(.90, .3),
    legend.box.just = "right")+
  xlab("Stimulus value")+
  ylab("P(response == 1)")


ses1 = data.frame(x = x, y = rbinom(length(x),1,psycho(x,-5,2,-5)), session = 1) 
ses2 = data.frame(x = x, y = rbinom(length(x),1,psycho(x,0,1.5,-10)), session = 2) 

scatter2 <- rbind(ses1,ses2) %>% mutate(session = as.factor(session)) %>% 
  ggplot(aes(x=x, y=y, col = session, fill = session)) +
  geom_point() +
  geom_smooth(method = "glm", 
    method.args = list(family = "binomial")) +theme_classic()+
  theme(text = element_text(size = 10),
        legend.position = c(.90, .3),
    legend.box.just = "right")+
  xlab("Stimulus value")+
  ylab("P(response == 1)")




w = 2 #width
c = 12
f_o = 6 #first offset
s_o = 3 #first offset
t_o = 2 #first offset


layout = c(area(1, c-w, 1, c+w),
         
  area(2, c-f_o-w-1, 2, c-f_o+w+1),
  area(2, c+f_o-w-1, 2, c+f_o+w+1),
  
  area(3, c-f_o-w/2-s_o-1, 3, c-f_o+w/2-s_o+1),
  area(3, c-f_o-w/2+s_o-1, 3, c-f_o+w/2+s_o+1),
  
  area(3, c+f_o-w/2-s_o-1, 3, c+f_o+w/2-s_o+1),
  area(3, c+f_o-w/2+s_o-1, 3, c+f_o+w/2+s_o+1),
  
  area(4, c-f_o-w-3, 5, c-f_o+w+3),
  area(4, c+f_o-w-3, 5, c+f_o+w+3),
  
  area(1, 26, 1, 26),
  area(1, 25, 1, 25),
  area(2, 26, 2, 26),
  area(2, 25, 2, 25),
  area(3, 26, 3, 26),
  area(3, 25, 3, 25),
  area(4, 25, 5, 26)
  )

#sigma[between]
plot(layout)


# Create a ggplot with a single geom_text layer
text1 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "Population", size = 4,
             angle = 270)+
  theme_void()

text2 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "sigma[between]", parse = T, size = 4,
             angle = 270)+
  theme_void()


# Create a ggplot with a single geom_text layer
text3 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "Subject", size = 4,
             angle = 270)+
  theme_void()

text4 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "sigma[within]", parse = T, size = 4,
             angle = 270)+
  theme_void()




# Create a ggplot with a single geom_text layer
text5 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "Session", size = 4,
             angle = 270)+
  theme_void()

text6 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "sigma[epsilon]", parse = T, size = 4,
             angle = 270)+
  theme_void()


text7 = ggplot(data.frame()) +
  annotate(geom = "text", x = 0, y = 0, label = "Trial level", size = 4,
             angle = 270)+
  theme_void()


#plot(layout)
p5_nested_hier = pop+sub1+sub2+sub1_p1+sub1_p2+sub2_p1+sub2_p2+scatter1+scatter2+
  text1+text2+text3+text4+text5+text6+text7+
  plot_layout(design = layout)


p5_nested_hier
```


```{r, fig.height=7, fig.width=7}


saveRDS(p5_nested_hier, file = here::here("Figures","figure_5_nested_hierarchical.RDS"))

ggsave(here::here("Figures","figure_5_nested_hierarchical.png"), plot = p5_nested_hier, dpi = 600, width = 7.2, height = 7.2)


```

