---
title: "Parameter recovery ICC nopathfinder"
output: html_document
date: "2024-03-19"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr,patchwork, gamlss,truncnorm,extraDistr,flextable,lmerTest,lme4,Matrix,pracma,brms,HDInterval)
```

## R Markdown

```{r}
source(here::here("Analyses","ICC analysis","Run_ICC_nopathfinder.R"))

```

# Single fit
```{r}

load("~/Master-thesis/workspace psychometric/ICC_nopathfinder.RData")

parameters = map_dfr(results,4)

xs = c(-10,2,-3.5)
ys = c(40,6,2)
of = c(4,0.6,0.7)

text_size = 3

correlation_nounc = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>%
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8),
         parameter =  str_remove(variable, "_unconstrained")) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  group_by(parameter) %>% 
  summarize(correlation = cor.test(value,mean)$estimate, sd = (cor.test(value,mean)$conf.int[2]-cor.test(value,mean)$conf.int[1])/3.96) %>% mutate(x = xs, y = ys)




samples = 1000

correlation_unc = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>% 
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8),
         parameter =  str_remove(variable, "_unconstrained")) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  group_by(parameter) %>% 
  mutate(sub = 1:n()) %>% rowwise() %>% mutate(esti_unc = list(rnorm(samples,mean,sd)),
                                               id = list(1:samples)) %>% unnest() %>% 
  group_by(id,parameter) %>% 
  summarize(corr = cor.test(value, esti_unc)$estimate[[1]]) %>% ungroup() %>% group_by(parameter) %>% 
  summarize(mean = mean(corr), sd = sd(corr))%>% mutate(x = xs, y = ys-of)
  


single_sub_model = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>% 
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8),
         parameter =  str_remove(variable, "_unconstrained")) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  ggplot(aes(col = parameter))+
  geom_pointrange(aes(x = value,y = mean, ymin = q5,ymax = q95))+
  geom_point(aes(x = value,y = mean), col = "black", alpha = 0.5)+
  facet_wrap(~parameter, scales = "free", labeller = label_both)+geom_abline()+
  theme_classic()+
  geom_text(data = correlation_nounc, aes(x = x, y = y,label = paste0("r (without) = ", round(correlation,2)," (",round(sd,2), ")")), size = text_size, col = "black")+
  geom_text(data = correlation_unc, aes(x = x, y = y,label = paste0("r (with) = ", round(mean,2)," (",round(sd,2), ")")), size = text_size)+
  theme(legend.position = "none")+
  ylab("Recovered value")+
  xlab("Simulated value")
  
single_histogram = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>% 
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8),
         parameter =  str_remove(variable, "_unconstrained")) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  mutate(model = "Single fit")


```


# Hierarchical
```{r}

parameters = results[[1]][[2]]%>% dplyr::select(-c("resp","prob","X","trials.1")) %>% distinct()

x = c(-9,1.8,-3.2)
y = c(45,5,3.5)
of = c(7,0.4,0.9)

correlation = results[[1]][[3]] %>% 
  dplyr::select(parameter,correlation_q97,correlation_q2,correlation_mean,ucnertainty_added)%>% 
  rename(mean = correlation_mean, q5 = correlation_q2, q95 = correlation_q97) %>% mutate(xs = c(x,x), ys = c(y,y-of))

y = y-2*of

ICC = results[[1]][[1]] %>% filter(grepl("ICC",variable)) %>% mutate(parameter = str_sub(variable, 5,nchar(variable))) %>% dplyr::select(mean,q5,q95,residual_variance,parameter,variable)%>% arrange(residual_variance,parameter) %>% 
  mutate(xs = c(x,x), ys = c(y,y-of))

nested_hier_model = parameters %>% pivot_longer(cols = contains("_uncon")) %>% 
  filter(name == paste0("real_",parameter,"_uncon"))%>% mutate(sessions = as.factor(sessions)) %>% 
  ggplot(aes(col = sessions))+
  geom_pointrange(aes(x = value,y = mean, ymin = q5,ymax = q95))+
  geom_point(aes(x = value,y = mean), col = "black", alpha = 0.5)+
  facet_wrap(~parameter, scales = "free", labeller = label_both)+geom_abline()+
  theme_classic()+
    geom_text(data = correlation %>% filter(ucnertainty_added == F), aes(x = xs, y = ys,label = paste0("r (without) = ", round(mean,2)," [",round(q5,2),";",round(q95,2), "]")), size = text_size, col = "black")+
    geom_text(data = correlation %>% filter(ucnertainty_added == T), aes(x = xs, y = ys,label = paste0("r (with) = ", round(mean,2)," [",round(q5,2),";",round(q95,2), "]")), size = text_size, col = "black")+  
    geom_text(data = ICC %>% filter(residual_variance == F), aes(x = xs, y = ys,label = paste0("ICC_1 = ", round(mean,2)," [",round(q5,2),";",round(q95,2), "]")), size = text_size, col = "black")+
    geom_text(data = ICC %>% filter(residual_variance == T), aes(x = xs, y = ys,label = paste0("ICC_2 = ", round(mean,2)," [",round(q5,2),";",round(q95,2), "]")), size = text_size, col = "black")+
  theme(legend.position = "top",
        legend.direction="horizontal",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,-5,-5,-5))+
  ylab("Recovered value")+
  xlab("Simulated value")
  
    


hier_histogram = parameters %>% pivot_longer(cols = contains("_uncon")) %>% 
  filter(name == paste0("real_",parameter,"_uncon"))%>% 
  mutate(sessions = as.factor(sessions), model = "Hierarchical")


histogram = single_histogram %>%
  ggplot(aes(x = sd, fill = model))+
  geom_histogram(col = "black", position = "identity", alpha = 0.5)+
  geom_histogram(data = hier_histogram, aes(x = sd), col = "black", position = "identity", alpha = 0.5)+
  facet_wrap(~parameter, scales = "free", labeller = label_both)+
  theme_classic()+xlab("Estimation uncertainty")
  


```





```{r, fig.width=7.2, fig.height=7.2}
library(patchwork)

p1 = single_sub_model+ggtitle("Single Fit model")+theme(plot.title=element_text(hjust=0.5))
p2 = nested_hier_model+ggtitle("Nested Hierarchical model")+theme(plot.title=element_text(hjust=0.5))
p3 = histogram


pp = p1/p2

pp
p3

ggsave(here::here("Figures","parameter_recovery_v1.PNG"),p1,width = 7.2,height = 5)
ggsave(here::here("Figures","parameter_recovery_v2_nested.PNG"),p2,width = 7.2,height = 5)


ggsave(here::here("Figures","Estimation_uncertainty_v1.PNG"),p3,width = 7.2,height = 4)


```

