---
title: "tables"
output: html_document
date: "2024-04-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse, flextable)

```

## R Markdown

#table 1
```{r}

library(flextable)
# Create data frame
data <- data.frame(
  Parameter = c("Alpha", "Beta", "Lapse"),
  Mean = c(0, 2, -4),
  Sd = c(10, 0.6, 2),
  Transformation = c("x", "Log(x)", "Logit^-1(x) / 2")
)


write.csv(data, here::here("tables","table1.csv"))

# Create flextable
ft <- flextable(data)
ft

saveRDS(ft,here::here("tables","table1.rds"))
```



#table 2
```{r}

library(flextable)
# Create data frame
data <- data.frame(
  Parameter = c("Alpha", "Beta", "Lapse", "Intercept", "BetaRT", "Sigma", "Non-decision-time"),
  Mean = c(0, "[1 ; 3]", -4, -2, "[1 ; 1.5]", -1, -1),
  Sd = c(10, 0.6, 2, 0.5, 0.3, 0.5, 0.5),
  Transformation = c("x", "Log(x)", "Logit^-1(x) / 2", "X", "Log(x)", "Log(x)", "Logit^-1(x) * minRT")
)


write.csv(data, here::here("tables","table2.csv"))

# Create flextable
ft <- flextable(data)
ft

saveRDS(ft,here::here("tables","table2.rds"))
```


# table 3
```{r}
load(here::here("Analyses","Legrand reanalysis","workspace","full_workspace.RData"))

d = rbind(
  rbind(d1,d2,d3,d4,d5,d6),
  rbind(ddq_full,ddq_rt,ddq),
  rbind(ICC, ICC_rt, ICC_full)
)%>% filter(variable %in% c("alpha", "beta") & propergated_uncertainty == TRUE)


d$model = as.factor(d$model)
d$structure = as.factor(d$structure)

levels(d$model)
levels(d$structure)

d$structure <- factor(d$structure, levels = c("Single","Hierarchical","Nested Hierarchical"))

d$text <- as.character(d$text)

d

table = d %>% arrange(structure,model,lapse) %>% mutate(propergated_uncertainty = NULL) %>% 
  pivot_wider(names_from = "variable",values_from = "text") %>% 
  select(alpha,beta,lapse,model,structure)

library(flextable)

write.csv(table, file = here::here("tables","table3.csv"))

flextable::flextable(table) %>% width(1:2, width = 1.5)


table3 = read.csv(here::here("tables","table3.csv")) %>% mutate(X = NULL)


table3 = flextable::flextable(table3) %>% width(1:2, width = 1.5)

saveRDS(table3,here::here("tables","table3.rds"))
```

# Supplementary table 1
```{r}

```


# table 4
```{r}

library(flextable)
# Create a flextable

df = data.frame(
  " " = c("Model result (significant)", "Model result (in-significant)"),
  "Reality (effect)" = c("1-\U03B2", "\U03B2"), # Unicode representation for beta
  "Reality (no effect)" = c("\U03B1", "1-\U03B1") # Unicode representation for alpha
)

names(df) = c(" ", "Reality (effect)","Reality (no effect)")
df


write.csv(df, here::here("tables","table4.csv"))

# Create flextable
ft <- flextable(df)
ft

saveRDS(ft,here::here("tables","table4.rds"))

```

#table 5
```{r}
load(here::here("realshit","Power analysis","pathfinder","reaction time","power_analysis_psi","Full poweranalysis workspace.RData"))



table5_loo = loo::loo_compare(list(logs_expo = logs,
                      logs_power = logs_power,
                      logs_power_noint = logistic_power_noint,
                      additive = additiveloo,
                      addititve_multiplicative = add_multloo))
df = data.frame(table5_loo)

df
rownames(df) = rownames(table5_loo)

df = df %>% rownames_to_column("models") %>% select(models,elpd_diff,se_diff)


write.csv(df, here::here("tables","table5.csv"))

# Create flextable
ft <- flextable(df)
ft

saveRDS(ft,here::here("tables","table5.rds"))


```

