---
title: "Visualize"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes, furrr,bridgesampling, rstan, brms, faux,LRO.utilities,reticulate, tictoc,rockchalk)
  
  
source(here::here("realshit","Power analysis","pathfinder","reaction time", "pathfinder_rt_datasets_scripts.R"))

```

## R Markdown

```{r}
results = list.files(here::here("realshit","Power analysis","pathfinder","reaction time","results"), full.names = TRUE)


bigdf = data.frame()
for(i in 1:length(results)){
  resultss = readRDS(results[i])
  
  effectsizes <- str_extract_all(results[i], "(?<=\\=)\\s*([0-9]+(?:\\.[0-9]+)?)")[[1]]
  df = map_dfr(resultss,bind_rows)
  
  if(as.numeric(effectsizes[1]) != df$real_effectsize_alpha[1]){
    print("ERROR")
  }
  
  if(as.numeric(effectsizes[2]) != df$real_effectsize_beta[1]){
    print("ERROR")
  }
  
  bigdf = rbind(bigdf,df)
}

bigdf %>% ggplot(aes(x = obs_effectsize_alpha, fill = as.factor(real_effectsize_alpha)))+geom_histogram(col = "black", position = "identity",alpha =0.75)

bigdf %>% ggplot(aes(x = obs_effectsize_beta, fill = as.factor(real_effectsize_beta)))+geom_histogram(col = "black", position = "identity",alpha =0.75)

bigdf %>% ggplot(aes(x = obs_effectsize_alpha, y = p_alpha, col = as.factor(real_effectsize_beta)))+geom_point()

bigdf %>% ggplot(aes(x = obs_effectsize_beta, y = p_beta, col = as.factor(real_effectsize_beta)))+geom_point()

# other direction of beta
aa = bigdf %>% filter(variable == "gm[4]") %>% select(q95, iter) %>% rename(p_beta2 = q95)

inner_join(aa,bigdf) %>% ggplot(aes(x = obs_effectsize_beta, y = p_beta2, col = as.factor(real_effectsize_beta)))+geom_point()

```

