---
title: "Visualize"
output: html_document
date: "2024-03-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes, furrr,bridgesampling, rstan, brms, faux,LRO.utilities,reticulate)

source(here::here("realshit","Power analysis","pathfinder","reaction time", "pathfinder_rt_datasets_scripts.R"))
source(here::here("realshit","Power analysis","pathfinder","reaction time", "pathfinder_rt_fit_scripts.R"))
  
```

## R Markdown


```{r}

files = list.files(here::here("realshit","Power analysis","pathfinder","reaction time", "results"), full.names = TRUE)



bigdf = data.frame()
for(i in 1:length(files)){
    df <- bind_rows(lapply(readRDS(files[i]), function(x) x[[1]]))
    bigdf = rbind(bigdf,df)
  }

bigdf %>% ggplot(aes(x = obs_effectsize_alpha, y = p_alpha, col = as.factor(real_effectsize_beta)))+geom_point()

bigdf %>% ggplot(aes(x = obs_effectsize_alpha, y = p_alpha, col = obs_effectsize_beta))+geom_point()


bigdf %>% ggplot(aes(x = obs_effectsize_beta, y = p_beta))+geom_point()+facet_wrap(~real_effectsize_beta)


bigdf %>% mutate(signifi_alpha = ifelse(p_alpha < 0.05, 1, 0),
                 signifi_beta = ifelse(p_beta < 0.05, 1, 0),
                 ) %>% 
  group_by(real_effectsize_beta,real_effectsize_alpha) %>% 
  summarize(power_alpha = sum(signifi_alpha) / n(),
            power_beta = sum(signifi_beta) / n()) %>% 
  ggplot(aes(x = real_effectsize_alpha, y = real_effectsize_beta, fill = power_alpha))+geom_raster()




bigdf %>% mutate(signifi_alpha = ifelse(p_alpha < 0.05, 1, 0),
                 signifi_beta = ifelse(p_beta < 0.05, 1, 0),
                 ) %>% 
  group_by(real_effectsize_beta,real_effectsize_alpha) %>% 
  summarize(power_alpha = sum(signifi_alpha) / n(),
            power_beta = sum(signifi_beta) / n()) %>% 
  ggplot(aes(x = real_effectsize_alpha, y = real_effectsize_beta, fill = power_alpha))+geom_raster()

bigdf %>% mutate(signifi_alpha = ifelse(p_alpha < 0.05, 1, 0),
                 signifi_beta = ifelse(p_beta < 0.05, 1, 0),
                 ) %>% 
  group_by(real_effectsize_beta,real_effectsize_alpha) %>% 
  summarize(power_alpha = sum(signifi_alpha) / n(),
            power_beta = sum(signifi_beta) / n()) %>% 
  ggplot(aes(x = real_effectsize_alpha, y = real_effectsize_beta, fill = power_beta))+geom_raster()



aa = bigdf %>% filter(variable == "gm[4]" | variable == "gm[3]") %>% 
  dplyr::select(variable, mean,real_effectsize_beta) %>% 
  pivot_wider(names_from = "variable",values_from = "mean") %>% 
  unnest()
  
aa$gm5 = (aa$`gm[3]`+aa$`gm[4]`)

aa %>% group_by(real_effectsize_beta) %>% summarize(mean = mean(gm5))

```

