---
title: "Parameter recovery single"
output: html_document
date: "2024-03-19"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr,patchwork, gamlss,truncnorm,extraDistr,flextable,lmerTest,lme4,Matrix,pracma,brms,HDInterval)
```

## R Markdown

```{r}
source(here::here("realshit","Run_single_nopathfinder.R"))

parameters = expand.grid(trials = c(100),
                         replicate = 1:100)

parameters <- parameters[sample(nrow(parameters)), ]

parameters = parameters %>% mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)

cores = 4
  
plan(multisession, workers = cores)
  
possfit_model = possibly(.f = together, otherwise = "Error")

#test = together(data_list[[25]])

results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

save.image("~/Master-thesis/workspace psychometric/Single_sub.RData")
```



# real plot
```{r}
load("~/Master-thesis/workspace psychometric/Single_sub.RData")

parameters = map_dfr(results,1)

xs = c(0,2,-4.5)
ys = c(40,6,1.2)
of = c(4,0.4,0.7)

correlation_nounc = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>%
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8)) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  group_by(variable) %>% 
  summarize(correlation = cor.test(value,mean)$estimate, sd = (cor.test(value,mean)$conf.int[2]-cor.test(value,mean)$conf.int[1])/3.96) %>% mutate(x = xs, y = ys)




samples = 1000

correlation_unc = parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>% 
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8)) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% 
  group_by(variable) %>% 
  mutate(sub = 1:n()) %>% rowwise() %>% mutate(esti_unc = list(rnorm(samples,mean,sd)),
                                               id = list(1:samples)) %>% unnest() %>% 
  group_by(id,variable) %>% 
  summarize(corr = cor.test(value, esti_unc)$estimate[[1]]) %>% ungroup() %>% group_by(variable) %>% 
  summarize(mean = mean(corr), sd = sd(corr))%>% mutate(x = xs, y = ys-of)
  


parameters %>% filter(mean_div == 0) %>% pivot_longer(cols = contains("_uncon")) %>% 
  mutate(variable_uncon = ifelse(grepl("_uncon",variable), variable, NA)) %>% 
  mutate(variable_uncon =  str_sub(variable_uncon, 1,nchar(variable_uncon)-8)) %>% 
  filter(name == paste0("real_",variable_uncon)) %>% filter(mean < 1000 & mean > -1000) %>% 
  ggplot(aes(col = variable))+
  geom_pointrange(aes(x = value,y = mean, ymin = q5,ymax = q95))+
  geom_point(aes(x = value,y = mean), col = "black", alpha = 0.5)+
  facet_wrap(~variable, scales = "free")+geom_abline()+
  theme_classic()+
  geom_text(data = correlation_nounc, aes(x = x, y = y,label = paste0("r (without) = ", round(correlation,2)," (",round(sd,2), ")")), size = 4, col = "black")+
  geom_text(data = correlation_unc, aes(x = x, y = y,label = paste0("r (with) = ", round(mean,2)," (",round(sd,2), ")")), size = 4)+
  theme(legend.position = "none")
  


```
