---
title: "ICC PR"
output: html_document
date: "2024-03-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr,patchwork, gamlss,truncnorm,extraDistr,flextable,lmerTest,lme4,Matrix,pracma)
```

## R Markdown

```{r}
source(here::here("realshit","run_ICC_psychometric.R"))

parameters = expand.grid(subs = c(10,30,50),
                         trials = seq(20,200,20),
                         replicate = 1:5) %>% 
  mutate(id = rev(1:nrow(.)))


data_list <- split(parameters, parameters$id)

# cores = 12
  
# plan(multisession, workers = cores)
  
possfit_model = possibly(.f = together, otherwise = "Error")

# results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))
# save.image(here::here("workspace psychometric","ICC_psycho_lowtrials_finished_beta=3.RData"))
# 

# rstudioapi::restartSession()
```


```{r, fig.height=6, fig.width=8}
source(here::here("realshit","Visualize_ICC_psychometric.R"))

load("~/HDDM_stan/workspace psychometric/ICC_psycho_lowtrials_finished_beta=1.RData")
ICC1 = ICC(results,"beta = 1")
correlation1 = Correlations(results,"beta = 1")
ICC_raw1 = ICC_raw(results,"beta = 1")
trialwise_alpha1 = plot_trialwise(results,"alpha")
trialwise_beta1 = plot_trialwise(results,"beta")
trialwise_lambda1 = plot_trialwise(results,"lambda")


load("~/HDDM_stan/workspace psychometric/ICC_psycho_lowtrials_finished_beta=2.RData")
ICC2 = ICC(results,"beta = 2")
correlation2 = Correlations(results,"beta = 2")
ICC_raw2 = ICC_raw(results,"beta = 2")


load("~/HDDM_stan/workspace psychometric/ICC_psycho_lowtrials_finished_beta=3.RData")
ICC3 = ICC(results,"beta = 3")
correlation3 = Correlations(results,"beta = 3")
ICC_raw3 = ICC_raw(results,"beta = 3")
trialwise_alpha3 = plot_trialwise(results,"alpha")
trialwise_beta3 = plot_trialwise(results,"beta")
trialwise_lambda3 = plot_trialwise(results,"lambda")



rbind(correlation1,correlation2,correlation3) %>%  filter(ucnertainty_added == T) %>% 
  group_by(trials,subs,parameter, ucnertainty_added, string) %>% 
  summarize(mean = mean(correlation_mean), q2 = mean(correlation_q2), q97 = mean(correlation_q97)) %>% 
  ggplot(aes(x = trials, y = mean, ymin = q2, ymax = q97, col = as.factor(subs)))+geom_pointrange()+facet_grid(string~parameter)+
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,by = 0.2))+theme_classic()+
  geom_hline(yintercept = 0.9, linetype = 2)+
  geom_hline(yintercept = 0.75, linetype = 2)+
  geom_hline(yintercept = 0.5, linetype = 2)




rbind(ICC1,ICC2,ICC3) %>% ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = subs))+
  geom_pointrange() + facet_grid(string~parameter)+
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,by = 0.2))+theme_classic()+
  geom_hline(yintercept = 0.9, linetype = 2)+
  geom_hline(yintercept = 0.75, linetype = 2)+
  geom_hline(yintercept = 0.5, linetype = 2)


rbind(ICC_raw1,ICC_raw2,ICC_raw3) %>% filter(grepl("ICC", variable), residual_variance == T) %>% 
  mutate(subs = as.factor(subs)) %>% 
  group_by(trials,subs,variable, string) %>% 
  summarize(mean = mean(mean), q5 = mean(q5), q95 = mean(q95)) %>%
  ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = subs))+
  geom_pointrange() + facet_grid(string~variable)+
  scale_y_continuous(limits = c(0,1), breaks = seq(0,1,by = 0.2))+theme_classic()+
  geom_hline(yintercept = 0.9, linetype = 2)+
  geom_hline(yintercept = 0.75, linetype = 2)+
  geom_hline(yintercept = 0.5, linetype = 2)


```


```{r, fig.height=6, fig.width=8}
trialwise_alpha1
trialwise_beta1
trialwise_lambda1
```


```{r, fig.height=6, fig.width=8}
trialwise_alpha3
trialwise_beta3
trialwise_lambda3

```



```{r}

rbind(ICC_raw1,ICC_raw2,ICC_raw3) %>% filter(grepl("resid", variable) & subs == 50) %>% 
  mutate(subs = as.factor(subs)) %>% 
  group_by(trials,subs,variable, string) %>% 
  summarize(mean = mean(mean), q5 = mean(q5), q95 = mean(q95)) %>%
  ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = string))+
  geom_pointrange() + facet_wrap(~variable, scales = "free_y")+theme_classic()



rbind(ICC_raw1,ICC_raw2,ICC_raw3) %>% filter(grepl("resid", variable) & subs == 10) %>% 
  mutate(subs = as.factor(subs)) %>% 
  group_by(trials,subs,variable, string) %>% 
  summarize(mean = mean(mean), q5 = mean(q5), q95 = mean(q95)) %>%
  ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = string))+
  geom_pointrange() + facet_wrap(~variable, scales = "free_y")+theme_classic()




rbind(ICC_raw1,ICC_raw2,ICC_raw3) %>% filter(grepl("within", variable) & subs == 50) %>% 
  mutate(subs = as.factor(subs)) %>% 
  group_by(trials,subs,variable, string) %>% 
  summarize(mean = mean(mean^2), q5 = mean(q5^2), q95 = mean(q95^2)) %>%
  ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = string))+
  geom_pointrange() + facet_wrap(~variable, scales = "free_y")+theme_classic()


rbind(ICC_raw1,ICC_raw2,ICC_raw3) %>% filter(grepl("within", variable) & subs == 10) %>% 
  mutate(subs = as.factor(subs)) %>% 
  group_by(trials,subs,variable, string) %>% 
  summarize(mean = mean(mean^2), q5 = mean(q5^2), q95 = mean(q95^2)) %>%
  ggplot(aes(x = trials, y = mean, ymin = q5, ymax = q95, col = string))+
  geom_pointrange() + facet_wrap(~variable, scales = "free_y")+theme_classic()
```

